
DOS_DISPSTR     =       09h
DOS_OPENFILE    =       3dh
DOS_CLOSEFILE   =       3eh
DOS_READFILE    =       3fh

ACC_READONLY    =       0 shl 0
ACC_WRITEONLY   =       1 shl 0
ACC_READWRITE   =       2 shl 0
ACC_COMPAT      =       0 shl 4
ACC_DENYRW      =       1 shl 4
ACC_DENYWRITE   =       2 shl 4
ACC_DENYREAD    =       3 shl 4
ACC_DENYNONE    =       4 shl 4
ACC_CHILDINH    =       0 shl 7
ACC_NOCHILDINH  =       1 shl 7

;----------------------------------------------------------------------------
MAXPATH         =       79

