demo.exe:   main_c.obj int_a.obj pit_c.obj video_a.obj video_c.obj math_a.obj &
            math_c.obj &
            tunnel_a.obj tunnel_c.obj bump_a.obj bump_c.obj flame_a.obj &
            object_c.obj vector_a.obj vector_c.obj texmap_a.obj &
            data_a.obj data2_a.obj meshdata.obj &
